import {createStorefrontClient} from '@shopify/hydrogen';
import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the server build file is generated by `remix vite:build`
// eslint-disable-next-line import/no-unresolved
import * as build from "../build/server";

type Context = EventContext<Env, string, unknown>;

const getStoreFrontClient = async (context: Context) => {
  return createStorefrontClient({
    cache: await caches.open('hydrogen'),
    publicStorefrontToken: context.env.PUBLIC_STOREFRONT_API_TOKEN,
    storeDomain: `https://${context.env.PUBLIC_STORE_DOMAIN}`,
  });
};

export const onRequest = createPagesFunctionHandler({ 
  build,
  getLoadContext: async (context: Context) => ({
    storefront: (await getStoreFrontClient(context)).storefront,
    env: process.env,
  }), 
});
