import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the server build file is generated by `remix vite:build`
// eslint-disable-next-line import/no-unresolved
import * as build from "../build/server";

async function authenticate(context) {
  context.data = {lower:{data:"some data"}};
  return await context.next();
}

export const onRequest = [createPagesFunctionHandler({ build }), authenticate];
